site_name: DIMPACS
nav:
    - Autenticación: 'index.md'
    - Responsable: 'responsable.md'
    - Pacientes: 
        - Estado Civil: 'EstadoCivil.md'
        - Tipos de pacientes: 'TiposPacientes.md'
        - Crear Paciente: 'CrearPaciente.md'
        - Obtener un paciente: 'ObtenerPaciente.md'


 
theme: material
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
