site_name: DIMPACS
nav:
    - Autenticación: 'index.md'
    - Responsable: 'responsable.md'

 
theme: material
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
